### ISSUE TITLE
TypeError: stream.on is not a function

### ISSUE THREAD

**Issue by mradzinski** [imagemin/imagemin-jpegoptim#13]
This happens when I try to use to use jpegoptim on Linux.

```
TypeError: stream.on is not a function
    at Readable.wrap (/home/***/node_modules/readable-stream/lib/_stream_readable.js:753:10)
    at wrap (/home/***/node_modules/stream-combiner2/index.js:67:29)
    at combine (/home/***/node_modules/stream-combiner2/index.js:29:18)
    at Function.module.exports.obj (/home/***/node_modules/stream-combiner2/index.js:22:10)
    at Imagemin.createStream (/home/***/node_modules/imagemin/index.js:103:24)
    at Imagemin.run (/home/***/node_modules/imagemin/index.js:77:20)
    at DestroyableTransform.through.obj.percent (/home/***/node_modules/gulp-imagemin/index.js:56:12)
    at DestroyableTransform._transform (/home/***/node_modules/through2-concurrent/through2-concurrent.js:30:15)
    at DestroyableTransform.Transform._read (/home/***/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/***/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
```

Gulp task:
```
  var path = require('path');
  var gulpif = require('gulp-if');
  var pngquant = require('imagemin-pngquant');
  var jpegoptim = require('imagemin-jpegoptim');

  gulp.task('imagemin', function() {
    return gulp.src(path.join(dirs.source, dirs.images, '**/*.{jpg,jpeg,gif,svg,png}'))
      .pipe(plugins.changed(dest))
      .pipe(gulpif(args.production, plugins.imagemin({
        progressive: true,
        svgoPlugins: [{removeViewBox: false}],
        use: [
          pngquant({ speed: 10 }),
          jpegoptim({max:90})
        ]
      })))
      .pipe(gulp.dest(dest));
  });
```

**Comment by shinnn** [comment]
https://github.com/search?q=org%3Aimagemin+stream.on+is+not+a+function&type=Issues
